// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZoN8vntXA0QnN_RIFlxBN9BGTB3uaAhw',
    appId: '1:305166207004:web:f17d282b31287ec8f8b7d9',
    messagingSenderId: '305166207004',
    projectId: 'e-summit-26',
    authDomain: 'e-summit-26.firebaseapp.com',
    storageBucket: 'e-summit-26.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCneqS4a2g6EDycFZ-pS7XK82gAw2ER1mk',
    appId: '1:305166207004:android:8afaa78043157fedf8b7d9',
    messagingSenderId: '305166207004',
    projectId: 'e-summit-26',
    storageBucket: 'e-summit-26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu6g6zEjn4P5jesb2Aqi55C6frdHicZIQ',
    appId: '1:305166207004:ios:f777e41f8e7f18b3f8b7d9',
    messagingSenderId: '305166207004',
    projectId: 'e-summit-26',
    storageBucket: 'e-summit-26.firebasestorage.app',
    iosBundleId: 'com.example.eSummit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu6g6zEjn4P5jesb2Aqi55C6frdHicZIQ',
    appId: '1:305166207004:ios:25afb773bedad0e5f8b7d9',
    messagingSenderId: '305166207004',
    projectId: 'e-summit-26',
    storageBucket: 'e-summit-26.firebasestorage.app',
    iosBundleId: 'com.example.esummit26',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZoN8vntXA0QnN_RIFlxBN9BGTB3uaAhw',
    appId: '1:305166207004:web:9c68bbff3bf07024f8b7d9',
    messagingSenderId: '305166207004',
    projectId: 'e-summit-26',
    authDomain: 'e-summit-26.firebaseapp.com',
    storageBucket: 'e-summit-26.firebasestorage.app',
  );

}